# Generated by Django 5.2.16 on 2026-09-07 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crashincident',
            name='source',
            field=models.CharField(default='511GA / n8n Webhook', max_length=255),
        ),
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('GOOGLE', 'Google Ads'), ('META', 'Meta (Facebook & Instagram)'), ('TIKTOK', 'TikTok Ads'), ('SNAPCHAT', 'Snapchat Ads')], max_length=50)),
                ('headline', models.CharField(max_length=255)),
                ('media_url', models.URLField(default='https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=800&q=80')),
                ('call_number', models.CharField(default='+1 (404) 555-TOWS', max_length=50)),
                ('form_url', models.URLField(default='http://localhost:8000/lead-form/')),
                ('impressions', models.IntegerField(default=1250)),
                ('clicks', models.IntegerField(default=84)),
                ('leads_count', models.IntegerField(default=6)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='crashes.crashincident')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('service_requested', models.CharField(default='Emergency Towing & Assistance', max_length=255)),
                ('platform_source', models.CharField(default='Meta Ads', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='crashes.adcampaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NearbyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('TOWING', 'Car Towing Service'), ('HOSPITAL', 'Hospital / Emergency Care'), ('REPAIR', 'Auto Repair Shop'), ('LEGAL', 'Accident Legal Assistance')], max_length=50)),
                ('distance_miles', models.FloatField(default=2.5)),
                ('phone', models.CharField(default='+1 (404) 555-0199', max_length=50)),
                ('address', models.CharField(default='Georgia, USA', max_length=255)),
                ('crash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_locations', to='crashes.crashincident')),
            ],
        ),
    ]
