# Generated by Django 5.2.16 on 2026-09-07 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0002_alter_crashincident_source_adcampaign_lead_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adcampaign',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='cta_type',
            field=models.CharField(choices=[('FORM', 'Fill Lead Contact Form'), ('CALL', 'Call Operator Now'), ('WEBSITE', 'Visit Assistance Website')], default='FORM', max_length=50),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='daily_budget',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='campaign_media/'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='name',
            field=models.CharField(default='Georgia Crash Rapid Campaign', max_length=255),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='primary_text',
            field=models.TextField(default='Emergency Roadside Towing & Hospital Assistance available within 5 miles of Georgia incident.'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='target_radius_miles',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, default='Lead generated via Ad Preview interaction'),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(default='NEW', max_length=50),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='crash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='crashes.crashincident'),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='platform',
            field=models.CharField(choices=[('META', 'Meta (Facebook & Instagram)'), ('GOOGLE', 'Google Ads'), ('TIKTOK', 'TikTok Ads'), ('SNAPCHAT', 'Snapchat Ads')], default='META', max_length=50),
        ),
    ]
