# Generated by Django 5.2.16 on 2026-09-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0003_alter_adcampaign_options_adcampaign_cta_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbylocation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nearbylocation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nearbylocation',
            name='category',
            field=models.CharField(choices=[('TOWING', 'Tow Yard / Recovery Service'), ('HOSPITAL', 'Hospital / Emergency Medical'), ('POLICE', 'Police Station / Patrol Precinct'), ('REPAIR', 'Auto Repair Shop'), ('LEGAL', 'Accident Legal Assistance')], max_length=50),
        ),
    ]
