# Generated by Django 5.2.16 on 2026-09-08 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0004_nearbylocation_latitude_nearbylocation_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaign',
            name='ab_test_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AutomationRuleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=255)),
                ('trigger_reason', models.CharField(max_length=500)),
                ('action_taken', models.TextField()),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crashes.adcampaign')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
    ]
