# Generated by Django 5.2.16 on 2026-09-08 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0005_adcampaign_ab_test_active_automationrulelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAdsAccountConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_token', models.CharField(default='MOCK_DEV_TOKEN_GA_511_CRASH', max_length=255)),
                ('client_id', models.CharField(blank=True, default='', max_length=255)),
                ('client_secret', models.CharField(blank=True, default='', max_length=255)),
                ('refresh_token', models.CharField(blank=True, default='', max_length=255)),
                ('customer_id', models.CharField(default='987-654-3210', max_length=100)),
                ('is_sandbox', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleAdsCampaignSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_campaign_id', models.CharField(max_length=100)),
                ('google_ad_group_id', models.CharField(max_length=100)),
                ('bidding_strategy_type', models.CharField(default='MAXIMIZE_CONVERSIONS', max_length=100)),
                ('target_cpa_amount', models.DecimalField(decimal_places=2, default=15.0, max_digits=8)),
                ('gaql_last_query', models.TextField(blank=True, default='SELECT campaign.id, metrics.impressions, metrics.clicks FROM campaign')),
                ('sync_status', models.CharField(default='SYNCED', max_length=50)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_sync', to='crashes.adcampaign')),
            ],
        ),
    ]
