# Generated by Django 5.2.16 on 2026-09-08 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0006_googleadsaccountconfig_googleadscampaignsync'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAdsAccountConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(default='987654321012345', max_length=255)),
                ('app_secret', models.CharField(blank=True, default='meta_app_secret_hash_ga_511', max_length=255)),
                ('access_token', models.CharField(default='EAABwz1234567890_MOCK_META_SYSTEM_USER_TOKEN', max_length=500)),
                ('ad_account_id', models.CharField(default='act_10203040506070', max_length=100)),
                ('pixel_id', models.CharField(default='1122334455667788', max_length=100)),
                ('page_id', models.CharField(default='georgia_emergency_towing_page_id', max_length=100)),
                ('is_sandbox', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetaAdsCampaignSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_campaign_id', models.CharField(max_length=100)),
                ('meta_adset_id', models.CharField(max_length=100)),
                ('meta_ad_id', models.CharField(max_length=100)),
                ('objective', models.CharField(default='OUTCOME_LEADS', max_length=100)),
                ('capi_last_event_id', models.CharField(blank=True, default='', max_length=255)),
                ('sync_status', models.CharField(default='SYNCED', max_length=50)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_sync', to='crashes.adcampaign')),
            ],
        ),
    ]
