# Generated by Django 5.2.16 on 2026-09-08 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0007_metaadsaccountconfig_metaadscampaignsync'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapchatAdsAccountConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(default='snap_client_id_ga_511_crash', max_length=255)),
                ('client_secret', models.CharField(blank=True, default='snap_secret_key_12345', max_length=255)),
                ('access_token', models.CharField(default='SNAP_ACCESS_TOKEN_EAAB_511_MOCK', max_length=500)),
                ('refresh_token', models.CharField(blank=True, default='', max_length=500)),
                ('ad_account_id', models.CharField(default='e3b0c442-98fc-4c14-96fe-789a12345678', max_length=100)),
                ('pixel_id', models.CharField(default='98765432-1111-2222-3333-444455556666', max_length=100)),
                ('organization_id', models.CharField(default='org_ga_emergency_towing_inc', max_length=100)),
                ('is_sandbox', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SnapchatAdsCampaignSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snap_campaign_id', models.CharField(max_length=100)),
                ('snap_adset_id', models.CharField(max_length=100)),
                ('snap_ad_id', models.CharField(max_length=100)),
                ('buy_model', models.CharField(default='AUCTION', max_length=100)),
                ('capi_last_event_id', models.CharField(blank=True, default='', max_length=255)),
                ('sync_status', models.CharField(default='SYNCED', max_length=50)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snap_sync', to='crashes.adcampaign')),
            ],
        ),
    ]
